version: '3.8'
services:
  currency-exchange-service:
    image: phamngochai3010yka/mm2-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-networks
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
    restart: always

  currency-conversion-service:
    image: phamngochai3010yka/mm2-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-networks
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
    restart: always

  api-gateway:
    image: phamngochai3010yka/mm2-api-gateway:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-networks
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
      spring.zipkin.baseUrl: http://zipkin-server:9411/
    restart: always

  naming-server:
    image: phamngochai3010yka/mm2-naming-server:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-networks
    restart: always

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-networks
    restart: always

networks:
  currency-networks:
